version: '3.4'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: StoreLine
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

  storelineapi:
    build:
      context: .
      dockerfile: StoreLineAPI/Dockerfile
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=StoreLine;Username=postgres;Password=admin"
    ports:
      - "7036:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  storelineclient:
    build:
      context: ./SLine
      dockerfile: Dockerfile
    ports:
      - "5001:3000"

  proxy:
    image: nginx:mainline
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /path/to/your/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"

volumes:
  db_data:
